spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/maven_kotlin_erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password: localDbPassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false